### ISSUE TITLE
Other useful git commands

### ISSUE THREAD

**Issue by splitcircle** [k88hudson/git-flight-rules#225]
First and foremost, thanks for making this guide! I have two git aliases that I use that I think may be of use here. Let me know if they fit, and if so I can make a PR to add them!

Delete all remote branches that have been merged in:
```delete-merged-branches = "!f() { git checkout --quiet master && git branch --merged | grep --invert-match '\\*' | xargs -n 1 git branch --delete; git checkout --quiet @{-1}; }; f"```

And, show all the work/commits you have done for the day: 
```day = "!sh -c 'git log --reverse --no-merges --branches=* --date=local --after=\"yesterday 11:59PM\" --author=\"`git config --get user.name`\"'"```

**Comment by RichardLitt** [comment]
Works for me! I use a similar command for the first one, too, but I hadn't seen the last. Add the aliases? :)

**Comment by deiga** [comment]
The second alias makes more sense to be written as: `day = log --reverse --no-merges --branches=* --date=local --since=midnight --author=\"$(git config --get user.name)\"`

- Git doesn't need to subshell for git commands :)
- `--since=midnight` is more timezone friendly, not all places use AM and PM

**Comment by ChrisCallanJr** [comment]
@deiga good to know! I'll use that as the alias I add, thank you!

**Comment by RichardLitt** [comment]
If anyone wants to add these aliases into the document, feel free to do so. Then we can close this out. :)
