### ISSUE TITLE
Contributing Guide

### ISSUE THREAD

**Issue by lucasMesquitaBorges** [k88hudson/git-flight-rules#272]
I would like some general contributing guide, almost every topic of flight rules it's about technical doubts.
How I'm starting with GitHub recently, i never now how to start contributing to some repository that i'm interesed.
I know that every repository has they own rules and patterns of coding and this isn't the problem, but how i'm not already a contributer from that repository, how could I start being assigned to an issue?
I believe my first PR should be related with features and after being a contributer start being assigned with issues.
Did I misunderstand something of the general concept of github contributing?

**Comment by diegogsann** [comment]
@lucasMesquitaBorges probably we can do it in #268
i am opening a new pull request now. we can enhance it.

**Comment by lucasMesquitaBorges** [comment]
@diegogsann PR #274 is very good. I don't know if is exclusivity of flight rules being more technical than conceptual, but would be nice add tips explaining repositories that has roadmaps and other contributing flow. A flight rule topic related to something like "General Flow of Github Contributing"
I don't know if is just obvious, but wasn't for me at beginning.

If you believe this type of content would be usefull, i could write a sketch.

**Comment by RichardLitt** [comment]
@lucasMesquitaBorges You have some really good points here. I think that what you're looking for would be awesome! And there are resources like this. For instance, https://opensource.guide/

Unfortunately, this probably isn't the best place for this. This is for how to use Git, not GitHub. These are two different things. Git is the software that powers GitHub; GitHub is the community that uses the software on a particular website. I think that these should stay separate, because they are actually a bit different. 

Take a look at https://opensource.guide. I hope it helps. :)
